from pathlib import Path


DEFAULT_CODE_DIR = Path("data/code")
DEFAULT_ARTIFACT_ROOT = Path("output/code_rag")

DEFAULT_SOURCE_DIR = DEFAULT_ARTIFACT_ROOT / "source"
DEFAULT_EVIDENCE_DIR = DEFAULT_ARTIFACT_ROOT / "evidence"
DEFAULT_REVIEW_DIR = DEFAULT_ARTIFACT_ROOT / "review"
DEFAULT_AUDIT_DIR = DEFAULT_ARTIFACT_ROOT / "audit"
DEFAULT_INDEX_DIR = DEFAULT_ARTIFACT_ROOT / "index"
DEFAULT_EVALUATION_DIR = DEFAULT_ARTIFACT_ROOT / "evaluation"
DEFAULT_MODEL_CACHE_DIR = DEFAULT_ARTIFACT_ROOT / "models"
DEFAULT_EVALUATION_DATASET = Path("data/code_rag/evaluation_queries.yaml")

DEFAULT_SOURCE_ENTITIES_PATH = DEFAULT_SOURCE_DIR / "source_entities.jsonl"
DEFAULT_EVIDENCE_DOCUMENTS_PATH = DEFAULT_EVIDENCE_DIR / "evidence_documents.jsonl"
DEFAULT_EXCLUSIONS_PATH = DEFAULT_REVIEW_DIR / "excluded_entities.jsonl"
DEFAULT_DB_PATH = DEFAULT_INDEX_DIR / "code_knowledge.db"
